# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: task-management-api
spec:
  selector:
    app: task-management-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Or LoadBalancer/NodePort